[build-system]
requires = ["setuptools>=84"]
build-backend = "setuptools.build_meta"

[project]
name = "rapis"
version = "0.1.0"
description = "Minimalistic web framework"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "msgspec>=0.21.1",
]
license = "MIT"
license-files = ["LICENSE"]
keywords = ["web-framework", "web", "async", "asyncio", "rsgi", "granian", "http"]
authors = [
  {email = "shept@sinortax.ru"},
]
classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "Environment :: Web Environment",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Internet :: WWW/HTTP",
]
[project.urls]
Documentation = "https://github.com/sheptalo/rapis/wiki"
Source = "https://github.com/sheptalo/rapis"

[project.optional-dependencies]
standard = ["granian[uvloop]>=2.7.4"]

[dependency-groups]
dev = [
    "granian>=2.7.6",
    "pre-commit>=4.6.0",
    "pytest>=9.0.3",
    "ruff>=0.15.12",
    "ty>=0.0.34",
    "uvloop>=0.22.1",
]


[tool.ruff]
extend-exclude = ["build", "benchmarks"]
line-length = 79


[tool.ruff.lint]
select = [
    "A",
    "B",
    "BLE",
    "E",
    "F",
    "FURB",
    "G",
    "I",
    "ICN",
    "INP",
    "N",
    "PLE",
    "PLW",
    "Q",
    "T",
    "TID",
    "UP",
    "W",
    "ERA",
    "ASYNC",
    "SIM",
    "TD",
    "ARG",  # Unused arguments
    "C",    # Complexity
    "PIE",  # Flake8-pie
    "RET",  # Return
    "RSE",  # Raise
    "SLF",  # Self
    "YTT",  # Type testing
    "PERF",
    "ANN",
    "COM",
    "S"
]
ignore = [
"N805", "ANN401", "COM812", "S104", "TD003", "B008"
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["S101", "S311", "INP001"]

[tool.cibuildwheel]
archs = ["auto64"]
test-requires = ["pytest"]
test-command = [
    'python -c "import rapis._speedups"',
    "pytest {project}/tests",
]

[tool.mypy]
strict = "True"
